Fixed a regression where type change in :func:`errisinstance` caused `mypy` to fail.